site_name: "{{cookiecutter.friendly_name}}"

theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/logo.svg
  palette:
    primary: white
    accent: deep purple
  icon:
    repo: fontawesome/brands/github

repo_url: https://github.com/iterative/{{cookiecutter.project_name}}
repo_name: iterative/{{cookiecutter.project_name}}

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/iterative/

plugins:
  - search
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - section-index
  - mkdocstrings:
      handlers:
        python:
          options:
            show_submodules: no

watch:
  - src/{{cookiecutter.package_name}}
